name: CI
on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  change-detection:
    name: 🔍 Change
    uses: ./.github/workflows/reusable-change-detection.yml

  tests:
    name: 🇨 Test
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-tests) && github.event.action != 'closed'
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/reusable-cpp-ci.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  linter:
    name: 🇨 Lint
    permissions:
      contents: read
      pull-requests: write
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-linter) && github.event.action != 'closed'
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-cpp-linter.yml@f33c11c5cf68957b3074fff11ae43cfce2aaf593 # v2.2.3
    with:
      clang-version: 21
      cpp-linter-extra-args: "-std=c++20"

  template:
    name: 🏗️ Build and Test Templates
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-template) && github.event.action != 'closed'
    uses: ./.github/workflows/reusable-template-ci.yml

  docs:
    name: 📝 Build and Deploy Docs
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-docs)
    uses: ./.github/workflows/reusable-docs.yml
    permissions:
      contents: write
      pull-requests: write

  required-checks-pass: # This job does nothing and is only used for branch protection
    name: 🚦 Check
    if: always()
    needs:
      - change-detection
      - tests
      - linter
      - template
      - docs
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
        with:
          allowed-skips: >-
            ${{
              (github.event.action == 'closed'
              || !fromJSON(needs.change-detection.outputs.run-tests))
              && 'tests,' || ''
            }} ${{
              (github.event.action == 'closed'
              || !fromJSON(needs.change-detection.outputs.run-linter))
              && 'linter,' || ''
            }} ${{
              (github.event.action == 'closed'
              || !fromJSON(needs.change-detection.outputs.run-template))
              && 'template,' || ''
            }} ${{
             !fromJSON(needs.change-detection.outputs.run-docs)
              && 'docs,' || ''
            }}
          jobs: ${{ toJSON(needs) }}
